FROM sider/devon_rex_go:2.12.0

<%= render_erb 'images/Dockerfile.base.erb' %>

ARG LINT_TOOL_VERSION="1.23.1"

USER root
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v${LINT_TOOL_VERSION}

USER $RUNNER_USER
RUN golangci-lint --version

<%= render_erb 'images/Dockerfile.end.erb' %>
