module Runners
  class Processor::MetricsFileInfo < Processor
    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    FILE_COMMAND_VALID_PLAIN_TEXT_FORMATS: Array[String]

    private

    def generate_issue: (Pathname, (int | nil), String)-> Issue

    def analyze_line_of_code: (Pathname) -> (nil | int)

    def analyze_last_commit_datetime: (Pathname) -> String

    def is_text_file?: (Pathname) -> bool

    def path_str: (Pathname) -> String
  end
end
