FROM sider/devon_rex_base:2.28.0

# install file command (file type guesser)
USER root
RUN apt-get update -y && apt-get install -qq -y --no-install-recommends file
USER $RUNNER_USER

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.end.erb' %>
