<% analyzer = ENV.fetch('ANALYZER') %>
# Install the default version
COPY images/<%= analyzer %>/Pipfile /tmp/<%= analyzer %>/Pipfile
USER root
RUN cd /tmp/<%= analyzer %> && \
    pipenv install --system --skip-lock && \
    cd .. && \
    rm -rf /tmp/<%= analyzer %> && \
    <%= analyzer %> --version
