name: Build

on:
  push:
    branches: ["master"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  # https://gist.github.com/ybiquitous/c80f15c18319c63cae8447a3be341267
  # https://github.com/actions/runner/issues/774
  check_skip:
    runs-on: ubuntu-latest
    if: |
      !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]')
    steps:
      - run: |
          echo 'github.event_name: ${{ github.event_name }}'
          echo 'github.event:'
          cat <<'EOD'
          ${{ toJson(github.event) }}
          EOD

  build:
    runs-on: ubuntu-latest
    needs: check_skip
    strategy:
      fail-fast: false
      matrix:
        analyzer:
          - brakeman
          - checkstyle
          - clang_tidy
          - code_sniffer
          - coffeelint
          - cppcheck
          - cpplint
          - detekt
          - eslint
          - flake8
          - fxcop
          - golangci_lint
          - goodcheck
          - hadolint
          - haml_lint
          - javasee
          - jshint
          - ktlint
          - languagetool
          - misspell
          - metrics_fileinfo
          - phinder
          - phpmd
          - pmd_cpd
          - pmd_java
          - pylint
          - querly
          - rails_best_practices
          - reek
          - remark_lint
          - rubocop
          - scss_lint
          - shellcheck
          - stylelint
          - swiftlint
          - tslint
          - tyscan
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Define variables
        id: define_vars
        # See https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          tag="${GITHUB_REF#refs/*/}"
          tag="${tag///}"
          echo "::set-output name=tag::${tag}"
      - name: Print variables
        run: |
          echo "tag: ${{ steps.define_vars.outputs.tag }}"
      - name: Build Docker image
        run: |
          bundle exec rake dockerfile:generate dockerfile:verify docker:build
        env:
          ANALYZER: ${{ matrix.analyzer }}
          TAG: ${{ steps.define_vars.outputs.tag }}
      - name: Run smoke test
        run: bundle exec rake docker:smoke
        env:
          ANALYZER: ${{ matrix.analyzer }}
          TAG: ${{ steps.define_vars.outputs.tag }}
          DEBUG: true
          RUNNERS_TIMEOUT: 3m
      - name: Publish Docker image
        if: |
          steps.define_vars.outputs.tag == 'master' || startsWith(github.ref, 'refs/tags/')
        run: |
          bundle exec rake docker:push
        env:
          ANALYZER: ${{ matrix.analyzer }}
          TAG: ${{ steps.define_vars.outputs.tag }}
          TAG_LATEST: ${{ startsWith(github.ref, 'refs/tags/') }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
